from app import db, models
cat = models.Category(name = "Politics")
db.session.add(cat)
cat = models.Category(name = "Entertainment")
db.session.add(cat)
cat = models.Category(name = "Sports")
db.session.add(cat)
cat = models.Category(name = "Education")
db.session.add(cat)
cat = models.Category(name = "Spiritual")
db.session.add(cat)
cat = models.Category(name = "Mythological")
db.session.add(cat)
cat = models.Category(name = "Books")
db.session.add(cat)
cat = models.Category(name = "Web Technology")
db.session.add(cat)
db.session.commit()
u = models.User(name = "Animesh Kumar", email = "animesh0721@hotmail.com", password_hash = "qwe123")
db.session.add(u)
u = models.User(name = "Utkarsh Bansal", email = "utkbansal@ymail.com", password_hash = "rty456")
db.session.add(u)
p = models.Poll(body = "Which party should win the upcoming Delhi elections?", user_id = 1, cat_id = 1, anonymous = False)
db.session.add(p)
p = models.Poll(body = "Should mini skirts be allowed in college campus?", user_id = 1, cat_id = 4, anonymous = True)
db.session.add(p)
p = models.Poll(body = "Which is better as scripting language?", user_id = 2, cat_id = 8, anonymous = False)
db.session.add(p)
p = models.Poll(body = "Linux Debian vs. Fedora?", user_id = 2, cat_id = 4, anonymous = False)
db.session.add(p)
op = models.Choice(poll_id = 1, value = "Bhartiya Janata Party")
db.session.add(op)
op = models.Choice(poll_id = 1, value = "Aam Aadmi Party")
db.session.add(op)
op = models.Choice(poll_id = 1, value = "Indian National Congress")
db.session.add(op)
op = models.Choice(poll_id = 2, value = "Yes")
db.session.add(op)
op = models.Choice(poll_id = 2, value = "No")
db.session.add(op)
op = models.Choice(poll_id = 3, value = "Python")
db.session.add(op)
op = models.Choice(poll_id = 3, value = "Ruby")
db.session.add(op)
op = models.Choice(poll_id = 3, value = "PHP")
db.session.add(op)
op = models.Choice(poll_id = 4, value = "Debian")
db.session.add(op)
op = models.Choice(poll_id = 4, value = "Fedora")
db.session.add(op)
db.session.commit()

